export const regionCountries = [
  {
    region: 'Adriatic-Ionian Area',
    countries: [
      ['Croatia', '/countries/croatia'],
      ['Greece', '/countries/greece'],
      ['Italy', '/countries/italy'],
      ['Slovenia', '/countries/slovenia'],
      ['Albania', ''],
      ['Bosnia and Herzegovina', ''],
      ['Montenegro', ''],
      ['Republic of North Macedonia', ''],
      ['Serbia', ''],
    ],
  },
  {
    region: 'Alpine Space',
    countries: [
      ['Austria', '/countries/austria'],
      ['France', '/countries/france'],
      ['Germany', '/countries/germany'],
      ['Italy', '/countries/italy'],
      ['Slovenia', '/countries/slovenia'],
      ['Liechtenstein', ''],
      ['Switzerland', '/countries/switzerland'],
    ],
  },
  {
    region: 'Northern Periphery and Artic',
    countries: [
      ['Finland', '/countries/finland'],
      ['Ireland', '/countries/ireland'],
      ['Sweden', '/countries/sweden'],
      // ['United Kingdom', '/countries/united-kingdom'],
      ['Iceland', '/countries/iceland'],
      ['Norway', '/countries/norway'],
      ['Greenland', ''],
      ['Faroe Islands', ''],
    ],
  },
  {
    region: 'Atlantic',
    countries: [
      ['France', '/countries/france'],
      ['Ireland', '/countries/ireland'],
      ['Portugal', '/countries/portugal'],
      ['Spain', '/countries/spain'],
      // ['United Kingdom', '/countries/united-kingdom'],
    ],
  },
  // {
  //   region: 'Balkan-Mediterranean',
  //   countries: [
  //     ['Bulgaria', '/countries/bulgaria'],
  //     ['Cyprus', '/countries/cyprus'],
  //     ['Greece', '/countries/greece'],
  //     ['Albania', ''],
  //     ['Republic of North Macedonia', ''],
  //   ],
  // },
  {
    region: 'Baltic Sea',
    countries: [
      ['Denmark', '/countries/denmark'],
      ['Estonia', '/countries/estonia'],
      ['Finland', '/countries/finland'],
      ['Germany', '/countries/germany'],
      ['Latvia', '/countries/latvia'],
      ['Lithuania', '/countries/lithuania'],
      ['Poland', '/countries/poland'],
      ['Sweden', '/countries/sweden'],
      ['Norway', '/countries/norway'],
      // ['Russia', ''],
      // ['Belarus', ''],
    ],
  },
  {
    region: 'Central Europe',
    countries: [
      ['Austria', '/countries/austria'],
      ['Croatia', '/countries/croatia'],
      ['Czechia', '/countries/czech-republic'],
      ['Germany', '/countries/germany'],
      ['Hungary', '/countries/hungary'],
      ['Italy', '/countries/italy'],
      ['Poland', '/countries/poland'],
      ['Slovakia', '/countries/slovakia'],
      ['Slovenia', '/countries/slovenia'],
    ],
  },
  {
    region: 'Danube',
    countries: [
      ['Austria', '/countries/austria'],
      ['Bulgaria', '/countries/bulgaria'],
      ['Croatia', '/countries/croatia'],
      ['Czechia', '/countries/czech-republic'],
      ['Germany', '/countries/germany'],
      ['Hungary', '/countries/hungary'],
      ['Romania', '/countries/romania'],
      ['Slovakia', '/countries/slovakia'],
      ['Slovenia', '/countries/slovenia'],
      ['Bosnia and Herzegovina, ', ''],
      ['Montenegro', ''],
      ['Serbia', ''],
      ['Ukraine', ''],
      ['Republic of Moldova', ''],
    ],
  },
  {
    region: 'Mediterranean',
    countries: [
      ['Albania', ''],
      ['Bosnia and Herzegovina', ''],
      ['Bulgaria', '/countries/bulgaria'],
      ['Croatia', '/countries/croatia'],
      ['Cyprus', '/countries/cyprus'],
      ['France', '/countries/france'],
      ['Greece', '/countries/greece'],
      ['Italy', '/countries/italy'],
      ['Malta', '/countries/malta'],
      ['Montenegro', ''],
      ['Portugal', '/countries/portugal'],
      ['Republic of North Macedonia', ''],
      ['Slovenia', '/countries/slovenia'],
      ['Spain', '/countries/spain'],
      // ['United Kingdom', '/countries/united-kingdom'],
    ],
  },
  {
    region: 'North Sea',
    countries: [
      ['Belgium', '/countries/belgium'],
      ['Denmark', '/countries/denmark'],
      ['Germany', '/countries/germany'],
      ['France', '/countries/france'],
      ['Netherlands', '/countries/netherlands'],
      ['Sweden', '/countries/sweden'],
      // ['United Kingdom', '/countries/united-kingdom'],
      ['Norway', '/countries/norway'],
    ],
  },
  {
    region: 'North-West Europe',
    countries: [
      ['Belgium', '/countries/belgium'],
      ['France', '/countries/france'],
      ['Germany', '/countries/germany'],
      ['Ireland', '/countries/ireland'],
      ['Luxembourg', '/countries/luxembourg'],
      ['Netherlands', '/countries/netherlands'],
      ['Switzerland', '/countries/switzerland'],
      // ['United Kingdom', '/countries/united-kingdom'],
    ],
  },
  {
    region: 'South-West Europe',
    countries: [
      ['France', '/countries/france'],
      ['Portugal', '/countries/portugal'],
      ['Spain', '/countries/spain'],
      // ['United Kingdom', '/countries/united-kingdom'],
      ['Andorra', ''],
    ],
  },
  {
    region: 'Other regions',
    countries: [['', '']],
  },
];
